# Generated by Django 5.0.2 on 2024-02-25 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emailuploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=512)),
                ('email_body', models.CharField(max_length=2048)),
                ('email_class', models.CharField(choices=[('newsletter', 'Newsletter'), ('regular', 'Regular Email')], default='regular', max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_method', models.CharField(choices=[('logic', 'Logic-Based'), ('ml', 'Machine Learning Model')], default='logic', max_length=16, null=True)),
                ('ml_classifier', models.CharField(choices=[('none', 'None'), ('lr', 'Logistic Regression'), ('keras', 'Keras DL')], default='none', max_length=16, null=True)),
                ('classification_status', models.CharField(choices=[('not_done', 'Not Done'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='not_done', max_length=16, null=True)),
                ('email_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailuploader.emailfile')),
            ],
        ),
    ]
